### ISSUE TITLE
Could not find artifact org.rutebanken.superpom:superpom:pom:1.0.38 in central

### ISSUE THREAD

**Issue by hbruch** [entur/lamassu#140]
When trying to build via `mvn install`, the superpom could not be found.

Could you provide some documentation about prerequisites like e.g. configured maven-repositories or required related projects? Thanks.

**Comment by testower** [comment]
Hi!  Sorry for the late response.
We have switched to another groupId for the superpom, and this one should be available in maven central. Can you check?

**Comment by hbruch** [comment]
Thanks @testower, sorry for the late response from my side as well.

`mvn install` now fails with

```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project lamassu: Could not resolve dependencies for project org.entur:lamassu:jar:0.0.1-SNAPSHOT: Could not find artifact org.entur.helpers:logging:jar:1.0.77 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```
I managed to install it from [rutebanken-helpers](https://github.com/entur/rutebanken-helpers/releases/tag/1.0.77) and now have a successful build. 

To ease installation further, the helpers jars could be published to maven also.

**Comment by testower** [comment]
Thanks for pointing that out. We had a new groupId for that as well, which is already in maven central. I have updated the pom now to reflect this.

**Comment by hbruch** [comment]
Works fine now, thanks.

Fixed via https://github.com/entur/lamassu/commit/0effe720fba338ba9e59f28e22d875364f84b573 and https://github.com/entur/lamassu/commit/30147c34ed2c3f132002f79f610b074b74af1f25
