### ISSUE TITLE
/gbs/{system}/{feed}: Cache-Control max-age increases over time

### ISSUE THREAD

**Issue by derhuerst** [entur/lamassu#217]
I noticed that the `max-age` directive's value in the `Cache-Control` header sent by Lamassu *increases* over time and gets reset on every feed refresh.

```shell
curl 'http://localhost:8080/gbfs/donkey-republic-kiel/station_information' -I
# HTTP/1.1 200
# …
# Cache-Control: max-age=112, public 
# …
# Date: Wed, 23 Aug 2023 17:29:41 GMT

curl 'http://localhost:8080/gbfs/donkey-republic-kiel/station_information' -I
# HTTP/1.1 200
# …
# Cache-Control: max-age=138, public
# …
# Date: Wed, 23 Aug 2023 17:31:05 GMT

curl 'http://localhost:8080/gbfs/donkey-republic-kiel/station_information' -I
# HTTP/1.1 200
# …
# Cache-Control: max-age=77, public
# …
# Date: Wed, 23 Aug 2023 17:31:07 GMT
```

If I'm not mistaken, this does not make sense: The period of time that a client should cache the resource for should *decrease*, coming closer to the next scheduled feed refresh.

---

I'm using the default settings, I have merely customised `org.entur.lamassu.feedproviders` & `org.entur.lamassu.redis.master.host` for my local experiments.

**Comment by testower** [comment]
The value of the max-age directive is calculated using the last_updated and ttl fields of the gbfs file:

https://github.com/entur/lamassu/blob/master/src/main/java/org/entur/lamassu/controller/GBFSFeedController.java#L303

pseudo-code:

```
maxAge = currentTime - lastUpdated + ttl
```

My interpretation would be that between the first and second requests, there has been an upstream update, and that the second request is closer in time to that update than the first request is to the update previous to it. On the other hand, between the second and third requests, no updates have taken place, so the max-age is simply decreasing.

**Comment by derhuerst** [comment]
> On the other hand, between the second and third requests, no updates have taken place, so the max-age is simply decreasing.

But even if it was working this way, look at the `Date`: In 2 seconds passed time, it decreased from `138` to `77`..?

**Comment by derhuerst** [comment]
Anyways, on `master` (240cb86), it is not working as I would expect it intuitively. Thanks!

Also adding `Last-Modified` with the time of the last upstream refresh would be even more helpful, but I'd say it's not strictly necessary for correct client behaviour.

**Comment by testower** [comment]
> In 2 seconds passed time, it decreased from 138 to 77..?

The only possible explanation for that is that there was an upstream refresh in between.

> Also adding Last-Modified with the time of the last upstream refresh would be even more helpful

I agree, that would be nice

**Comment by testower** [comment]
@derhuerst Have a look at this branch where I've added Last-Modified header: https://github.com/entur/lamassu/tree/add-last-modified

**Comment by testower** [comment]
>  it is not working as I would expect it intuitively

I'm still struggling to understand how exactly you mean it is not working

**Comment by derhuerst** [comment]
> > it is not working as I would expect it intuitively
> 
> I'm still struggling to understand how exactly you mean it is not working

Sorry, I meant: it is *now* working as I would expect it intuitively. 🤦

**Comment by testower** [comment]
Aha well that’s good to know 😁 thanks for the feedback and for raising these issues!
