### ISSUE TITLE
auto discovery: support relative URLs

### ISSUE THREAD

**Issue by derhuerst** [entur/lamassu#238]
As of 3.0-RC, the GBFS spec merely defines the `url` field as "URL for the feed […]". It does not limit the field to *absolute* URLs, so my interpretation is that relative URLs (e.g. `system_information.json`, `./system_information.json` or `../foo/system_information.json`) should be valid.

I have also asked in the GBFS repo to clarify this: https://github.com/MobilityData/gbfs/pull/189#issuecomment-1707331520

```json5
{
  "data": {
    "en": {
      "feeds": [
        {
          "name": "system_information",
          "url": "./system_information.json"
        },
        // …
      ]
    }
  },
  // …
}
```

---

With the example above, Lamassu currently seems to fail fetching the feed with the following log message:

```json
{
	"serviceContext": {
		"service": "lamassu"
	},
	"message": "Failed to setup subscription, trying again in 5 seconds - systemId=deer\n",
	"reportLocation": {
		"filePath": "org.entur.lamassu.leader.FeedUpdater",
		"lineNumber": "130",
		"functionName": "createSubscription"
	},
	"severity": "WARNING"
}
```

**Comment by testower** [comment]
Thanks - I'll await the clarification on the spec. I have never expected it to work the way you suggest.

**Comment by futuretap** [comment]
We’ve interpreted the spec to require absolute URLs and don’t support relative URLs in our consumer code. We’re also not aware of any producer publishing relative URLs.

**Comment by testower** [comment]
It seems unlikely that this will be added in the spec, but in the event that it does, this issue may be reopened.
