### ISSUE TITLE
Handling non-unique vehicle type ids across feeds of same provider

### ISSUE THREAD

**Issue by hbruch** [entur/lamassu#271]
Lamassu assumes, that IDs in different feeds of the same provider are unique. While this seems to be a reasonable assumption for i.e. stations and vehicles, this is not the case for vehicle types.

E.g. Nextbike uses vehicle type id 150 in multiple feeds (which seems perfectly valid given it's the same type of vehicle in use in multiple places):

https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_fg/de/vehicle_types.json
https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_vn/de/vehicle_types.json 

In consequence, we see issues like:
 
```
ipl-lamassu-1             | {"serviceContext":{"service":"lamassu"},"message":"Caught exception in ForkJoinPool\njava.lang.IllegalStateException: java.lang.IllegalStateException: Duplicate key NBK:VehicleType:150 (attempted merging values VehicleType{id='NBK:VehicleType:150', formFactor=BICYCLE, riderCapacity=1, cargoVolumeCapacity=null, cargoLoadCapacity=null, propulsionType=HUMAN, ecoLabel=null, maxRangeMeters=null, name=TranslatedString{translation=[Translation{language='en', value='with Framelock'}]}, vehicleAccessories=null, gCO2km=null, vehicleImage='https://static.nextbike.net/app/biketypes/type/ch/150/h500.png', make='null', model='null', color='null', wheelCount=null, maxPermittedSpeed=null, ratedPower=null, defaultReserveTime=null, returnConstraint=null, vehicleAssets=null, defaultPricingPlan=null, pricingPlans=null} and VehicleType{id='NBK:VehicleType:150', formFactor=BICYCLE, riderCapacity=1, cargoVolumeCapacity=null, cargoLoadCapacity=null, propulsionType=HUMAN, ecoLabel=null, maxRangeMeters=null, name=TranslatedString{translation=[Translation{language='en', value='with Framelock'}]}, vehicleAccessories=null, gCO2km=null, vehicleImage='https://static.nextbike.net/app/biketypes/type/ch/150/h500.png', make='null', model='null', color='null', wheelCount=null, maxPermittedSpeed=null, ratedPower=null, defaultReserveTime=null, returnConstraint=null, vehicleAssets=null, defaultPricingPlan=null, pricingPlans=null})\n\tat java.base/jdk.internal.reflect.GeneratedConstructorAccessor188.newInstance(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)\n\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)\n\tat java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)\n\tat java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)\n\tat java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689)\n\tat java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)\n\tat java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)\n\tat java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)\n\tat java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)\n\tat java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)\n\tat org.entur.gbfs.GbfsSubscriptionManager.lambda$update$0(GbfsSubscriptionManager.java:68)\n\tat java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)\nCaused by: java.lang.IllegalStateException: Duplicate key NBK:VehicleType:150 (attempted merging values VehicleType{id='NBK:VehicleType:150', formFactor=BICYCLE, riderCapacity=1, cargoVolumeCapacity=null, cargoLoadCapacity=null, propulsionType=HUMAN, ecoLabel=null, maxRangeMeters=null, name=TranslatedString{translation=[Translation{language='en', value='with Framelock'}]}, vehicleAccessories=null, gCO2km=null, vehicleImage='https://static.nextbike.net/app/biketypes/type/ch/150/h500.png', make='null', model='null', color='null', wheelCount=null, maxPermittedSpeed=null, ratedPower=null, defaultReserveTime=null, returnConstraint=null, vehicleAssets=null, defaultPricingPlan=null, pricingPlans=null} and VehicleType{id='NBK:VehicleType:150', formFactor=BICYCLE, riderCapacity=1, cargoVolumeCapacity=null, cargoLoadCapacity=null, propulsionType=HUMAN, ecoLabel=null, maxRangeMeters=null, name=TranslatedString{translation=[Translation{language='en', value='with Framelock'}]}, vehicleAccessories=null, gCO2km=null, vehicleImage='https://static.nextbike.net/app/biketypes/type/ch/150/h500.png', make='null', model='null', color='null', wheelCount=null, maxPermittedSpeed=null, ratedPower=null, defaultReserveTime=null, returnConstraint=null, vehicleAssets=null, defaultPricingPlan=null, pricingPlans=null})\n\tat java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)\n\tat java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)\n\tat java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)\n\tat java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\n\tat java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)\n\tat java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)\n\tat java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)\n\tat java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)\n\tat java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)\n\tat org.entur.lamassu.leader.entityupdater.VehiclesUpdater.getVehicleTypes(VehiclesUpdater.java:275)\n\tat org.entur.lamassu.leader.entityupdater.VehiclesUpdater.addOrUpdateVehicles(VehiclesUpdater.java:144)\n\tat org.entur.lamassu.leader.entityupdater.EntityCachesUpdater.updateEntityCaches(EntityCachesUpdater.java:51)\n\tat org.entur.lamassu.leader.FeedUpdater.receiveUpdate(FeedUpdater.java:166)\n\tat org.entur.lamassu.leader.FeedUpdater.lambda$createSubscription$1(FeedUpdater.java:126)\n\tat org.entur.gbfs.GbfsSubscription.update(GbfsSubscription.java:104)\n\tat java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)\n\tat java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3612)\n\tat java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)\n\tat java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)\n\tat java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)\n\t... 5 common frames omitted\n","reportLocation":{"filePath":"org.entur.lamassu.leader.FeedUpdater","lineNumber":"95","functionName":"lambda$start$0"},"severity":"WARNING"}
```

Lamassu should be capable to handle identical vehicle types across different feeds of the same provider.

**Comment by testower** [comment]
But

* Which feed holds the truth about that particular vehicle type?
* Can we assume they are actually the same?

I'm not completely convinced about this - but don't have a solution either. I'd prefer for the data producer to actually NOT reuse IDs across feeds period, because anything else messes with semantics of GBFS.

**Comment by hbruch** [comment]
Good questions. Not sure how easy it would be to detect issues and only throw an error if different?
Of course, there will be moments in time when operators change vehicle type descriptions and they differ for a (hopefully short) period of time.

If this messes with GBFS semantics, is the ID uniqueness enforced or at least recommended in the spec? I'm not aware of such a statement.

**Comment by testower** [comment]
> If this messes with GBFS semantics, is the ID uniqueness enforced or at least recommended in the spec? I'm not aware of such a statement.

No but the spec does not provision for data sharing between feeds either. IMHO since the spec does not explicitly say that two entities with the same ID across two feeds are the same entity, we should not assume that they are.

Since systems are linked by manifest.json in v3.0, maybe it's a good idea to suggest that this is handled specifically. That is, IDs MUST be unique across all systems listed in manifest.json?

**Comment by hbruch** [comment]
> No but the spec does not provision for data sharing between feeds either. IMHO since the spec does not explicitly say that two entities with the same ID across two feeds are the same entity, we should not assume that they are.
If they not for sure represent the same entity, and ID duplication is currently not forbidden by the spec, should lamassu include the `system_id` in the `vehicle_type_id` to guarantee uniqueness across feeds?

> Since systems are linked by manifest.json in v3.0, maybe it's a good idea to suggest that this is handled specifically. That is, IDs MUST be unique across all systems listed in manifest.json?

I'll post this to the mobility data gbfs slack for discussion.

**Comment by tdelmas** [comment]
I had the same interrogation, specifically for `3.0-RC` with the introduction of the `manifest`, which links multiple systems.

Currently:
> An ID: [...] MUST be unique within like fields (for example, station_id MUST be unique among stations)

Which seams to imply that two stations cannot share the same ID between two systems linked with a manifest, and that looks like an error, or it was simply overlooked.

In my opinion:
> An ID: [...] MUST be unique within like fields **of the same system** (for example, station_id MUST be unique among stations of that system)

**Comment by testower** [comment]
In any case, we MUST avoid a situation where some ID can be reused across systems (whether or not linked by manifest.json), but that in *some* cases it means that they are the same entity, and in others they are not.

E.g. It can't be the case that the same vehicle type id across systems means they are the same, but the same station id across systems means they are not the same.

I mean, it makes less sense for the same station to appear in multiple systems, but nevertheless IDs should be treated the same whether they are vehicle type ids or station ids.

**Comment by testower** [comment]
One very simple fix would be to assign different codespaces to systems of the same operator where one cannot assume unique IDs across all systems.

**Comment by testower** [comment]
I really don't think we should assume that there is any shared data between systems - after all that's why they are separate systems. They are by definition separate operations. If they happen to share some pricing schemes or vehicle type data, then that should be considered coincidental, and I would still expect them not to share IDs. If that is not the case, then separate codespaces might be the only sane solution.

**Comment by hbruch** [comment]
Using different code spaces is an option to avoid these issues for now, yes. Nevertheless this is IMHO a workaround, as an information easily accessible for every entity that two systems are operated by the same operator (e.g. for filtering/styling purposes) would be lost.

**Comment by testower** [comment]
Codespace is a data separation mechanism, so fits the purpose. There's nothing preventing you from grouping them under the same operator id though?
