### ISSUE TITLE
Vehicles with propulsion type human should not state current_range_meters=0

### ISSUE THREAD

**Issue by hbruch** [entur/lamassu#502]
## Expected behavior
Vehicles with a `vehicle_type` that has `propulsion_type=human` should not state `current_range_meters=0`

## Observed behavior
Both `VehicleStatusFeedMappers`(v2.3 and v3.0) [set a missing current_range_meters to 0](https://github.com/entur/lamassu/blob/e8abc84f7b24ea9b941db277214c84ac4fab6aae/src/main/java/org/entur/lamassu/mapper/feedmapper/v3/VehicleStatusFeedMapper.java#L82) without regard to the vehicle's `propulsion_type`.

## Version of lamassu used (exact commit hash or JAR name)
e8abc84f7b24ea9b941db277214c84ac4fab6aae

**Comment by testower** [comment]
Good catch!

**Comment by hbruch** [comment]
Do you have a preference how to fix this? Personally, I just would not set the range to 0 if it is not given, as the feed provider is responsible for feed correctness. This is usually the approach lamassu takes.

Otherwise, the VehicleStatusMappers would not only require access to the vehicle status feed itself, but also to the vehicle types feed.

**Comment by testower** [comment]
I agree with your solution 👍
