### ISSUE TITLE
Configurable entity caching for stations

### ISSUE THREAD

**Issue by hbruch** [entur/lamassu#537]
**Is your feature request related to a problem? Please describe.**
For vehicles, the `vehicleEntityCacheMinimumTtl ` can be configured. For stations, the ttl is [currently hard coded to `300`](https://github.com/entur/lamassu/blob/master/src/main/java/org/entur/lamassu/leader/entityupdater/StationsUpdater.java#L226).

**Goal / high level use-case**
In our test/dev instances, we use an increased `org.entur.lamassu.feedupdateinterval` to reduce requests. This currently results in stations swept out from the cache.

**Describe the solution you'd like**
I suggest renaming `vehicleEntityCacheMinimumTtl` to `entityCacheMinimumTtl` and use it for both, stations and vehicles.

**Describe alternatives you've considered**
Two possible alternatives:
* merge  `vehicleEntityCacheMinimumTtl`, `org.entur.lamassu.feedCacheMinimumTtl` and the new param for stations cache into one single config parameter `org.entur.lamassu.cacheMinimumTtl` (not sure if there are use cases which require to define them differently(?))
* introduce a new `stationEntityCacheMinimumTtl`(I don't see a need to set it to a different value, but there might be use cases I'm not aware of)

**Comment by testower** [comment]
Leaning towards alternative 2, introducing 

> stationEntityCacheMinimumTtl

for no other reason than to not break any existing deployments and to maintain flexibility
